// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBImBnsQIUHBfmozoFTs8ZaCFef4zhpkjA',
    appId: '1:831855769213:web:3eebacd1d6c61a143b2314',
    messagingSenderId: '831855769213',
    projectId: 'imagenia-af2ee',
    authDomain: 'imagenia-af2ee.firebaseapp.com',
    storageBucket: 'imagenia-af2ee.firebasestorage.app',
    measurementId: 'G-BR7F5XV8LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMDI2iVcqQbtM6d9uqSbFQC-gnebF4lWY',
    appId: '1:831855769213:android:bc4954b8378f34623b2314',
    messagingSenderId: '831855769213',
    projectId: 'imagenia-af2ee',
    storageBucket: 'imagenia-af2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXMGV_8ab0mZ4BdzS8jHVYF5bv7aOal8',
    appId: '1:831855769213:ios:978a315ee4025ca03b2314',
    messagingSenderId: '831855769213',
    projectId: 'imagenia-af2ee',
    storageBucket: 'imagenia-af2ee.firebasestorage.app',
    iosBundleId: 'com.example.imageniaaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeXMGV_8ab0mZ4BdzS8jHVYF5bv7aOal8',
    appId: '1:831855769213:ios:978a315ee4025ca03b2314',
    messagingSenderId: '831855769213',
    projectId: 'imagenia-af2ee',
    storageBucket: 'imagenia-af2ee.firebasestorage.app',
    iosBundleId: 'com.example.imageniaaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBImBnsQIUHBfmozoFTs8ZaCFef4zhpkjA',
    appId: '1:831855769213:web:f3ac9a4edd436b6a3b2314',
    messagingSenderId: '831855769213',
    projectId: 'imagenia-af2ee',
    authDomain: 'imagenia-af2ee.firebaseapp.com',
    storageBucket: 'imagenia-af2ee.firebasestorage.app',
    measurementId: 'G-J12KL6PJ8J',
  );
}
